import { useEffect, useState } from 'react';
import { request } from '../lib/api';

export default function Dashboard() {
  const [data, setData] = useState(null), [error, setError] = useState(''), [source, setSource] = useState('demo_fixture');
  useEffect(() => { let active = true, running = false; async function load() { if (running) return; running = true; try { const value = await request('/api/dashboard'); if (active) { setData(value); setError(''); } } catch (e) { if (active) setError(e.message); } finally { running = false; } } load(); const timer = setInterval(load, 15000); return () => { active = false; clearInterval(timer); }; }, []);
  const logs = data?.logs.filter(r => r.data_source === source) || [];
  return <><p className="eyebrow">SUPERVISOR</p><h1>The site, together.</h1><p className="muted intro">Demo supervisor view · refreshes every 15 seconds · no authenticated access control.</p>{error && <p className="error-banner" role="alert">{error} Previously loaded information may be stale.</p>}{!data && !error && <p role="status">Loading site data…</p>}
    {data && <><p className="small-note">Updated {new Date(data.generated_at).toLocaleString()}. {data.coverage}</p><div className="day-summary">{['pending', 'in_progress', 'completed'].map(status => <div key={status}><strong>{data.tasks.filter(t => t.status === status).length}</strong><span>{status.replaceAll('_', ' ')}</span></div>)}</div>
    <section className="companion-card"><h2>Task progress</h2><div className="table-scroll"><table><thead><tr><th>Task</th><th>Operator</th><th>Status</th><th>Actual / estimate</th></tr></thead><tbody>{data.tasks.map(t => <tr key={t.task_id}><td>{t.task_type}</td><td>{t.operator_id}</td><td>{t.status}</td><td>{t.actual_time_min?.toFixed(1) ?? '—'} / {t.estimated_time_min} min</td></tr>)}</tbody></table></div></section>
    <section className="companion-card"><h2>Idle and safety observations</h2><label>Source<select value={source} onChange={e => setSource(e.target.value)}>{['demo_fixture', 'sample_replay', 'phone_estimate', 'simulation'].map(s => <option key={s}>{s}</option>)}</select></label>{data.operators.map(p => { const own = logs.filter(l => l.operator_id === p.operator_id); const idle = own.filter(l => l.idling_time_min !== null); const belts = own.filter(l => l.seatbelt_status); return <p key={p.operator_id}><strong>{p.operator_id}</strong> · Idle: {idle.length ? `${idle.reduce((sum, l) => sum + l.idling_time_min, 0).toFixed(1)} min across ${idle.length} records` : 'unknown'} · Unfastened snapshots: {belts.length ? belts.filter(l => l.seatbelt_status === 'unfastened').length : 'unknown'}.</p>; })}<div className="table-scroll"><table><thead><tr><th>Recorded</th><th>Operator</th><th>Idle min</th><th>Seatbelt</th></tr></thead><tbody>{logs.slice(0, 20).map(l => <tr key={l.id}><td>{new Date(l.timestamp).toLocaleString()}</td><td>{l.operator_id}</td><td>{l.idling_time_min ?? 'Unknown'}</td><td>{l.seatbelt_status ?? 'Unknown'}</td></tr>)}</tbody></table></div><p className="small-note">Snapshots are not distinct violations. Phone observations cannot measure fuel or seatbelts.</p></section>
    <section className="companion-card"><h2>Recent incident reports</h2>{data.incidents.length ? data.incidents.map(r => <article key={r.id}><h3>{r.type.replaceAll('_', ' ')} · {r.operator_id}</h3><p>{r.note}</p><p className="small-note">{new Date(r.created_at).toLocaleString()}{r.has_photo ? ' · Photo attached in Incident reports' : ''}</p></article>) : <p>No reports received.</p>}</section>
    <section className="companion-card"><h2>Training completions</h2>{data.completions.length ? data.completions.map(c => <p key={c.id}>{c.operator_id} · {c.score}% · {new Date(c.completed_at).toLocaleString()}</p>) : <p>No learning checks completed yet.</p>}</section></>}
  </>;
}
